apiVersion: apps/v1
kind: Deployment
metadata:
  name: not-important
  labels:
    sidecar-injected: true
spec:
  template:
    metadata:
      annotations:
        app.flomesh.io/port: "8080"      

