apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.flomesh.io/type: springboot

resources:
- ../resources/samples-config-service.yaml

patches:
  - path: ../patches/check-discovery-patch.yaml
    target:
      kind: Deployment