apiVersion: v1
kind: Service
metadata:
  labels:
    app: samples-bookinfo-details
  name: samples-bookinfo-details
spec:
  ports:
  - port: 8103
    protocol: TCP
    targetPort: 8103
  selector:
    app: samples-bookinfo-details
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: samples-bookinfo-details
  name: samples-bookinfo-details
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samples-bookinfo-details
  strategy: {}
  template:
    metadata:
      annotations:
        "app.flomesh.io/name": "samples-bookinfo-details"
        "app.flomesh.io/port": "8103"
      labels:
        app: samples-bookinfo-details
    spec:
      containers:
      - image: flomesh/samples-bookinfo-details:latest
        name: app
        resources: {}
        ports:
          - containerPort: 8103        
        env:
          - name: K8S_SAMPLES_DISCOVERY_SERVER_HOSTNAME
            value: 'samples-discovery-server'
          - name: K8S_SAMPLES_DISCOVERY_SERVER_PORT
            value: "8761"          
status: {}
