apiVersion: v1
kind: Service
metadata:
  labels:
    app: samples-bookinfo-ratings 
  name: samples-bookinfo-ratings
spec:
  ports:
  - port: 8101
    protocol: TCP
    targetPort: 8101
  selector:
    app: samples-bookinfo-ratings
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: samples-bookinfo-ratings
  name: samples-bookinfo-ratings
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samples-bookinfo-ratings
  strategy: {}
  template:
    metadata:
      annotations:
        "app.flomesh.io/name": "samples-bookinfo-ratings"
        "app.flomesh.io/port": "8101"
      labels:
        app: samples-bookinfo-ratings
    spec:
      containers:
      - image: flomesh/samples-bookinfo-ratings:latest
        name: app
        resources: {}
        ports:
          - containerPort: 8101        
        env:
          - name: K8S_SAMPLES_DISCOVERY_SERVER_HOSTNAME
            value: 'samples-discovery-server'
          - name: K8S_SAMPLES_DISCOVERY_SERVER_PORT
            value: "8761"            
status: {}
