apiVersion: v1
kind: Service
metadata:
  labels:
    app: samples-bookinfo-reviews
  name: samples-bookinfo-reviews
spec:
  ports:
  - port: 8102
    protocol: TCP
    targetPort: 8102
  selector:
    app: samples-bookinfo-reviews
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: samples-bookinfo-reviews
  name: samples-bookinfo-reviews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samples-bookinfo-reviews
  strategy: {}
  template:
    metadata:
      annotations:
        "app.flomesh.io/name": "samples-bookinfo-reviews"
        "app.flomesh.io/port": "8102"
      labels:
        app: samples-bookinfo-reviews
    spec:
      containers:
      - image: flomesh/samples-bookinfo-reviews:latest
        name: app
        resources: {}
        ports:
          - containerPort: 8102      
        env:
          - name: K8S_SAMPLES_DISCOVERY_SERVER_HOSTNAME
            value: 'samples-discovery-server'
          - name: K8S_SAMPLES_DISCOVERY_SERVER_PORT
            value: "8761"             
status: {}
