apiVersion: v1
kind: Service
metadata:
  labels:
    app: samples-config-service
  name: samples-config-service
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: samples-config-service
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: samples-config-service
  name: samples-config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samples-config-service
  strategy: {}
  template:
    metadata:
      labels:
        app: samples-config-service
    spec:
      containers:
      - image: flomesh/samples-config-service:latest
        name: app
        env:
          - name: K8S_SAMPLES_DISCOVERY_SERVER_HOSTNAME
            value: samples-discovery-server
          - name: K8S_SAMPLES_DISCOVERY_SERVER_PORT
            value: "8761"
          - name: K8S_SAMPLES_BOOKINFO_RATINGS_HOSTNAME
            value: samples-bookinfo-ratings
          - name: K8S_SERVICE_NAME
            value: samples-config-service        
        resources: {}
        ports:
          - containerPort: 8888
status: {}
