apiVersion: v1
kind: Service
metadata:
  labels:
    app: samples-discovery-server
  name: samples-discovery-server
spec:
  ports:
  - port: 8761
    protocol: TCP
    targetPort: 8761
  selector:
    app: samples-discovery-server
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: samples-discovery-server
  name: samples-discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samples-discovery-server
  strategy: {}
  template:
    metadata:
      labels:
        app: samples-discovery-server
    spec:
      containers:
      - image: flomesh/samples-discovery-server:latest
        name: app
        resources: {}
        env:
          - name: eureka.server.enableSelfPreservation
            value: 'false'
        ports:
          - containerPort: 8761        
status: {}
