apiVersion: apps/v1
kind: Deployment
metadata:
  name: not-important
  labels:
    sidecar-injected: true
spec:
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '6060'
    spec:
      volumes:
        - name: cache-volume
          emptyDir: {}
      containers:
        - image: flomesh/pipy-pjs:0.4.0-328
          name: sidecar
          command:
            - /usr/local/bin/pipy
            - http://pipy-repo.pipy:6060/repo/$(SERVICE_NAME)/
            - --admin-port=6060
          volumeMounts:
            - mountPath: /opt/data
              name: cache-volume            
          env:
            - name: TARGET_PORT
              value: '20880'
            - name: SERVICE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.annotations['app.flomesh.io/name']
            - name: _pod_ns
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: _pod_nodeName
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: _pod_name
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: _pod_serviceName
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.annotations['app.flomesh.io/name']
            - name: _pod_UID
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.uid
            - name: _pod_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: _pod_hostIP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
