apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../resources/samples-bookinfo-productpage.yaml

patches:
  - path: ../patches/check-gateway-patch.yaml
    target:
      kind: Deployment
  - path: ../patches/opentelemetry-patch.yaml
    target:
      kind: Deployment         