apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.flomesh.io/type: springboot

resources:
- ../resources/samples-api-gateway.yaml

patches:
  - path: ../patches/sidecar-patch.yaml
    target:
      kind: Deployment

  - path: ../patches/check-configservice-patch.yaml
    target:
      kind: Deployment
