apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: springboot

resources:
  - ./resources/namespace.yaml
  - ./discovery-service
  - ./config-service
  - ./api-gateway
  - ./apps
  - ./apps-v1
  - ./apps-v2
  - ./page