apiVersion: apps/v1
kind: Deployment
metadata:
  name: not-important
  labels:
    sidecar-injected: true
spec:
  template:
    spec:
      initContainers:
        - name: check-discovery
          image: busybox:latest
          command: [ "/bin/sh", "-c" ]
          args:
            - |-
              until nc -vz samples-discovery-server 8761; \
                do echo "Waiting for Discovery Service ready ..."; \
                sleep 5; \
              done;