apiVersion: apps/v1
kind: Deployment
metadata:
  name: not-important
  labels:
    sidecar-injected: true
spec:
  template:
    spec:
      initContainers:
        - name: check-config
          image: busybox:latest
          command: [ "/bin/sh", "-c" ]
          args:
            - |-
              until nc -vz samples-config-service 8888; \
                do echo "Waiting for config service ready ..."; \
                sleep 5; \
              done;