apiVersion: v1
kind: Service
metadata:
  name: ratings
  labels:
    app: ratings
    service: ratings
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: ratings
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings
  labels:
    app: ratings
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings
  template:
    metadata:
      annotations:
        app.flomesh.io/name: ratings
        app.flomesh.io/port: "9080"
      labels:
        app: ratings
    spec:
      containers:
      - name: app
        image: flomesh/examples-bookinfo-ratings:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080